name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get -v -t -d
      - name: Build package
        run: go build -v
      - name: Test package
        run: go test -v -coverprofile=coverage.out
      - name: Show coverage
        run: go tool cover -func=coverage.out
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && needs.build.result == 'success'
    env:
      IMAGE_TAG: docker.pkg.github.com/qusic/telegramauth/app
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . --tag $IMAGE_TAG
      - name: Push image
        run: docker push $IMAGE_TAG
